### ISSUE TITLE
Bootstrap command could create symlinks (in node_modules)

### ISSUE THREAD

**Issue by pomek** [cksource/mgit2#16]
After calling the bootstrap command, required packages are installed in `packages/` directory.

Tools like Webpack won't search the package in the custom directory. From Webpack point of view, packages would be installed in `node_modules` directory.

Bootstrap command after installation a package, could create a symlink:

```
|-- packages
|  |-- some-dependency
|  `-- @scope
|     `-- other-dependency
|-- node_modules
|  |-- some-dependency (symlink to /packages/some-dependency)
|  |-- @scope
|     `-- other-dependency (symlink to /packages/@scope/other-dependency)
|-- mgit.json
```

**Comment by Reinmar** [comment]
Those symlinks should be made for dependencies (and dev deps) found in `/package.json` which are installed in `/packages/*`.

I'd like to make such a feature request to Lerna, because that would be helpful also in e.g. https://github.com/ckeditor/ckeditor5-dev which uses `ckeditor5-dev-lint` itself. With some tweaks that would also make it possible to link to `ckeditor5-dev/packages/*` in `ckeditor5`. Right now we have this script:  https://github.com/ckeditor/ckeditor5/blob/master/scripts/switch-to-dev-dev.sh. But this is future – first we need to have it in mgit.

**Comment by pomek** [comment]
At this moment `bootstrap` command does not support install devDependencies - https://github.com/cksource/mgit2/blob/master/lib/commands/bootstrap.js#L57-L61.

In this case, should we also install devDeps?

I guess, create symlinks could be done in `afterExecute` hook. 
`afterExecute` knows which dependencies were installed. We need to read `/package.json`, filter out deps/devDeps which aren't installed (in `/packages/`) and create symlinks for these deps. Before create a symlink, a real package from node_modules has to be removed (because in some case it can exist).

**Comment by pomek** [comment]
I'm wrong. `afterExecute` knows all the packages which were processed. But this is not a problem, before starting a process, we need to filter out packages which weren't installed.

**Comment by Reinmar** [comment]
> In this case, should we also install devDeps?

I've noticed that. But in our case it's not a problem. We only need devDeps of the package we're testing, so only for the first level of `mgit boostrap` call in `ckeditor5-xxx`. In `ckeditor5` that doesn't matter, because all packages are listed in `mgit.json` and we don't use the `--recursive` option.

However, in general, when running `--recursive` it'd make sense to install dev deps too. The idea is that the repos in `package/*` should be fully functional and should fully utilise all packages which repository resolver returned.

**Comment by Reinmar** [comment]
In other words – in case of `--recursive` it will be the repository resolver which will decide whether to clone the repo or let npm install it.

**Comment by pomek** [comment]
Yeah. I understand. 

We will need to introduce some mechanism which allows running `bootstrap` command with the different configuration. 

I mean, initial bootstrap with `--recursive` will work for all packages. For dependencies, and dependencies those dependencies, etc. As you said, `--recursive` options makes sense only for the first level of dependencies. For deeper dependencies, we need to set `--recursive` to `false.`

My proposition (implementation details):

https://github.com/cksource/mgit2/blob/master/lib/commands/bootstrap.js#L60 - returns an array of packages. Instead of the array, it could return an object with additional options. These options will [modify the `data` object before calling the command](https://github.com/cksource/mgit2/blob/master/lib/index.js#L54).

WDYT?

**Comment by pomek** [comment]
No, I wrote something wrong.

Dev deps should be always installed (for packages found in `mgit.json`). Dependencies for these dependencies (found in `mgit.json`) should install dev deps too.

Let's simplify - dev deps always have to be installed. `--recursive` option does not affect on it.

**Comment by Reinmar** [comment]
This isn't necessary anymore – we're using Lerna. It turned out that if we add the main package to its `packages` it will consider it automatically.
